import React, { useContext, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { GlobalContext } from "../../context/GlobalContext";
import { Layout, Loader } from "../../components/import";
import { PrivateRoute } from "../../utils";
import GenreCard from '../../components/Card/GenreCard'
import genre from "../../sample/genre";
import { Genre } from '../../types'


import SpotifyWebApi from "spotify-web-api-node";
const spotifyApi = new SpotifyWebApi({
  clientId: "0c064b242e744e0ca6d6dbbc5458c704",
});

const Index = () => {

  const { accessToken, dispatch, loading } = useContext(GlobalContext);

  const shuffleArray = (arr: string[]) => arr.sort(() => Math.random() - 0.5);

  //const filterGenre = (allGenres: any[]) => allGenres.filter((single_genre: string)=> genre)

  useEffect(()=>{
    if(!accessToken) return;
    spotifyApi.setAccessToken(accessToken);

    spotifyApi.getAvailableGenreSeeds().then(data=>{
     let genre = shuffleArray(data.body.genres).slice(0, 20);
     //console.log(genre)
    })
  },[accessToken])

  return (
    <PrivateRoute>
      <Layout>
      <Head>
          <title>Apple music - browse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {loading.state === "load_genre" ? (
          <Loader />
        ):(
          <div className="bg-[#323232] pt-[90px] px-10 h-full" >
            <h1 className="text-[17px] font-semibold text-[#ffffffeb]">
              Browse by Genre
            </h1>
            <div className="grid 2xl:grid-cols-6 xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-2 gap-x-1 gap-y-10 row-auto grid-flow-row " >
              {genre.map((data: Genre, index: number)=>(
                <GenreCard data={data} key={index} />
              ))}
            </div>
          </div>
        )}
      </Layout>
    </PrivateRoute>
  );
};

export default Index;
