import { useContext, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Layout, Loader } from '../components/import'
import { PrivateRoute } from '../utils'
import { GlobalContext } from '../context/GlobalContext'





export default function Home() {
  


  return (
   <PrivateRoute>
     <Layout>
      <Head>
        <title>Apple music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#323232] pt-[90px] px-10 h-full" >
        <h1 className="text-4xl font-semibold text-[#ffffeb]" >Listen Now</h1>
        {/* <Loader /> */}
      </div>
    </Layout>
   </PrivateRoute>
  )
}
