import { useContext, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Layout } from '../components/import'
import { PrivateRoute } from '../utils'
import { GlobalContext } from '../context/GlobalContext'





export default function Home() {
  


  return (
   <PrivateRoute>
     <Layout>
      <Head>
        <title>Apple music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-12" >
        <h1 className="text-6xl" >Songs</h1>
      </div>
    </Layout>
   </PrivateRoute>
  )
}
